GRANT USAGE ON *.* TO 'keutour1'@'localhost' IDENTIFIED BY PASSWORD '*BCBA172D7BCECDA3895DC06497D208A7FBBF7015';
GRANT ALL PRIVILEGES ON `keutour1`.* TO 'keutour1'@'localhost';
GRANT ALL PRIVILEGES ON `keutour1\_%`.* TO 'keutour1'@'localhost';
GRANT USAGE ON *.* TO 'keutour1_sonkeu'@'localhost' IDENTIFIED BY PASSWORD '*1C6C2E85A528C3CB121DA2AF46C629A7B373B341';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE ROUTINE ON `keutour1\_sonkeu`.* TO 'keutour1_sonkeu'@'localhost';
